package exception_testing;

public class ExceptionThrower {
	
	void invokeMe(){
		throw new RuntimeException("Hello");
	}

	public static void main(String[] args) {
		
	}

}
